import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Anek_Telugu } from "next/font/google";
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';

import "./globals.css";

const anekTelugu = Anek_Telugu({
  subsets: ["latin"], 
  variable: "--font-caption",
});


const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Martin CHARRIER Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeistSans.variable} ${anekTelugu.variable} font-sans h-full bg-background text-foreground`}
      >
        <div className="h-full"> {children}</div>
        {/* {children} */}
      </body>
    </html>
  );
}
